version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-list-aws"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5o7xoj5nq4pn"
s3_prefix = "todo-list-aws/Prod"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
parameter_overrides = "stage=\"Prod\" serviceTest=\"todo-list-aws\""
